Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -71,7 +71,12 @@ jobs:
           export DBPORT=${{ secrets.DBPORT }}
           export PORT=8000
           
-          sudo docker load -i ~/myapp.tar
+          if [ -f ~/myapp.tar ]; then
+            sudo docker load -i ~/myapp.tar
+          else
+            echo "File ~/myapp.tar not found!"
+            exit 1
+          fi
           sudo docker stop myapp || true
           sudo docker rm myapp || true
           sudo docker run -d --name myapp -p 8080:8080 myapp:latest
